doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Descarga\Subscriber:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Subscriber/Entity'
                prefix: 'Descarga\Subscriber\Entity'
