### Subscriber Retrieve
GET http://localhost:8000/subscriber/4

### Subscriber Create
POST http://localhost:8000/subscriber

{
  "firstName": "Alef",
  "lastName": "Castelo",
  "email": "alefaraujocastelo@gmail.com"
}

### Subscriber Update
POST http://localhost:8000/subscriber/4

{
  "firstName": "Alef",
  "lastName": "Araujo"
}

### Subscriber List
GET http://localhost:8000/subscriber


### Subscriber Create
POST http://localhost:8000/graphql
Content-Type: application/graphql

{
  "query": "{\nhealthcheck {\nstatus\ntime\n}\n}"
}