healthcheck:
    path: /
    controller: Descarga\Rest\Action\HealthCheckAction

subscriber_create:
    path: /subscriber
    methods: [POST]
    controller: Descarga\Rest\Action\Subscriber\SubscriberCreateAction
