healthcheck:
    path: /
    controller: Descarga\Rest\Action\HealthCheckAction

subscriber_create:
    path: /subscriber
    methods: [POST]
    controller: Descarga\Rest\Action\Subscriber\SubscriberCreateAction

subscriber_retrieve:
    path: /subscriber/{id}
    methods: [GET]
    controller: Descarga\Rest\Action\Subscriber\SubscriberRetrieveAction
