parameters:
    env(ROOT_NAMESPACE): Descarga

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $graphqlSchemaPath: '%env(resolve:GRAPHQL_SCHEMA_PATH)%'
            $redisConnectionDns: '%env(resolve:REDIS_CONNECTION_DNS)%'

    Descarga\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'

    Descarga\Rest\Action\:
        resource: '../src/Rest/Action/'
        tags: [ 'controller.service_arguments' ]

    Descarga\GraphQL\:
        resource: '../src/GraphQL/'
        tags: [ 'graphql.resolvers' ]

    Predis\Client:
        arguments:
            - '$redisConnectionDns'
