parameters:
    env(ROOT_NAMESPACE): Descarga

services:
    _defaults:
        autowire: true
        autoconfigure: true


    Descarga\Rest\Action\:
        resource: '../src/Rest/Action/'
        tags: ['controller.service_arguments']

    Descarga\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'