parameters:
    env(ROOT_NAMESPACE): Descarga

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Descarga\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'

    Descarga\Rest\Action\:
        resource: '../src/Rest/Action/'
        tags: [ 'controller.service_arguments' ]