parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true


    Descarga\CMS\Rest\Action\:
        resource: '../src/Rest/Action/'
        tags: ['controller.service_arguments']

    Descarga\CMS\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'